freebsd_instance:
  image: freebsd-11-2-release-amd64

task:
  name: FreeBSD local deploy
  env:
    ALGO_SERVER: localhost
    ALGO_ENDPOINT: 127.0.0.1
  install_script:
    - pkg install -y python bash py27-pip py27-virtualenv
    - python -m pip install -U pip virtualenv
    - python -m pip install -r requirements.txt
  script:
    - ./tests/local-deploy.sh
  check_script:
    - true
