freebsd_instance:
  image: freebsd-11-2-release-amd64

task:
  name: FreeBSD local deploy
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: cat requirements.txt
    populate_script:
      - pkg install -y python3 bash py36-pip py36-virtualenv base64
      - python3 -m pip install -U pip3 virtualenv
      - python3 -m pip install -r requirements.txt
  env:
    ALGO_SERVER: localhost
    ALGO_ENDPOINT: 127.0.0.1
  # install_script:
  script:
    - ./tests/local-deploy.sh
  check_script:
    - true
